version: '3.3'
services:
  earth:
    image: alpine:3.12
    tty: true
    env_file:
      - .env
    environment:
      - DENOM=earth
      - CHAIN_ID=Earth
    working_dir: /workspace
    command: /workspace/scripts/setup_genesis.sh
    volumes:
      - ./.earth:/workspace/.earth
      - ./scripts:/workspace/scripts
      - ./build:/usr/local/bin
      - ./ibc-proxy:/workspace/ibc

  mars:
    image: alpine:3.12
    tty: true
    env_file:
      - .env
    environment:
      - DENOM=mars
      - CHAIN_ID=Mars
    working_dir: /workspace
    command: /workspace/scripts/setup_genesis.sh
    volumes:
      - ./.mars:/workspace/.mars
      - ./scripts:/workspace/scripts
      - ./build:/usr/local/bin
      - ./ibc-proxy:/workspace/ibc

  ibc:
    image: node:16.3.0-alpine3.13
    working_dir: /workspace
    tty: true
    ports:
      - 80:80
    volumes:
      - ./ibc-proxy/:/workspace
      - ./ibc-proxy/.ibc-setup:/root/.ibc-setup
      - ./smart-contracts:/root/contracts
    command: yarn start
    environment:
      - PORT=80

  # build:
  #   image: orai/orai:alpine-wasm
  #   tty: true
  #   # command: wget https://github.com/CosmWasm/wasmvm/releases/download/v0.14.0/libwasmvm_muslc.a -O /lib/libwasmvm_muslc.a
  #   volumes:
  #     - ./:/workspace
