[package]
name = "marketplace"
version = "0.1.0"
authors = ["blockscape <tu@orai.io>"]
edition = "2018"

exclude = [
  "contract.wasm",
  "hash.txt",
] # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version="0.14.0" }
cw-storage-plus = { version="0.6.1", features=["iterator"] }
cw20 = "0.6.1"
cw721 = "0.6.1"
schemars = "0.8.1"
serde = { version="1.0.103", default-features=false, features=["derive"] }
thiserror = { version="1.0.21" }

[dev-dependencies]
cosmwasm-schema = { version="0.14.0" }
